import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <div class="mx-80 mt-20">
        {children}
        <Header />
        </div>
      </body>
    </html>
  );
}
